name: Build image and push Bea image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build docker image
    runs-on: [self-hosted, linux, x64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '1'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Generate build ID
      id: prep
      run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"  
    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/theme-nextjs-bea:${{ steps.prep.outputs.BUILD_ID }}
        secrets: |
            "NEXT_PUBLIC_HCAPTCHA_SITEKEY=${{ secrets.NEXT_PUBLIC_HCAPTCHA_SITEKEY }}"
    - name: Clear cache
      id: clear-cache
      run: |
          sleep 90
          token=${PREZLY_API_TOKEN}
          theme_id=${PREZLY_THEME_ID}
          curl --request POST \
              --url https://admin-api.prezly.com/v1/themes/${theme_id}/clear-cache \
              --header "Authorization: Bearer ${token} \
              --header "Content-Type: application/json"
